services:
  - type: web
    name: axiomgfx-api
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn src.main:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: CORS_ORIGIN
        fromService:
          type: web
          name: axiomgfx-web
          property: url

  - type: web
    name: axiomgfx-web
    env: node
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NEXT_PUBLIC_API_BASE
        fromService:
          type: web
          name: axiomgfx-api
          property: url

